### ISSUE TITLE
Still trouble with symlinks & os.chmod()

### ISSUE THREAD

**Issue by johntconklin** [okcompute/p4clean#11]
Hi Pascal,

Even with your recent changes, I'm having troubles with os.chmod() changing the permissions of the targets of symbolic links.  The problem is that may UNIX systems (like RHEL 5.x) don't have os.lchmod(), so the code falls back to using os.chmod().

Since you've now imported the platform module, it may be worth only changing the mode if  platform.system() == 'Windows' especially since on UNIX systems, a file's mode doesn't effect whether it can be deleted. This avoids an additional filesystem operation, which may have non-trivial latency with a network filesystem. So even on Windows, it may be worth trying the os.remove() first, and only bother changing file modes and re-trying if the remove fails.

**Comment by okcompute** [comment]
Fixed
