### ISSUE TITLE
No log output...

### ISSUE THREAD

**Issue by johntconklin** [okcompute/p4clean#12]
Hi Pascal,

With your latest code, I'm not getting any output.  I had to add an explicit call to logger.setLevel() for the non-quiet case as well, like:

```
if args.quiet:
    logger.setLevel(logging.ERROR)
else:
    logger.setLevel(logging.INFO)
```

Sorry, no pull request for this one yet (but it's in my features/untracked_dir branch).

**Comment by okcompute** [comment]
Did you get the latest version? I have fixed this on my adding the same line you did but at line 43. Can you confirm you have with logger.setLeve(logging.INFO) set at line 43?

**Comment by okcompute** [comment]
Nevermind previous comment. I saw the code in your branch. Weird though that on your platform the setLevel(info) at the module level has no effect!

**Comment by okcompute** [comment]
fixed
