### ISSUE TITLE
shell_execute() hides stderr on failure.

### ISSUE THREAD

**Issue by johntconklin** [okcompute/p4clean#16]
One of my developers was having an issue with a new p4clean snapshot I installed today.  While debugging his issue, I discovered shell_execute() hides subprocess errors.  

It redirects stderr to stdout, but if a CalledProcessError exception is thrown, you don't see what the error is (even though the comment says "Do nothing, the error is already sent to stderr").  For the debug session, I caught the exception into a variable, and then was able to log the ex.output attribute which contained the text sent to stderr.  Once I knew why the spawned p4 command failed, it was easy to figure out how to get things working for him.

No pull request, as I'm not sure whether this is the way you want to handle the problem.

As for the user's error, it turns out to be a subtle interaction between symlinks to the client workspace, the shell's cached current working directory, and client Root and AltRoot settings.  Need to think about this more...

**Comment by okcompute** [comment]
Hi have a fix for this available soon. Working on it. I'm trying to find the right balance between catching exceptions or showing a proper user friendly message.

**Comment by okcompute** [comment]
Fixed: 2f033657ee653ab8bc64bd79531522aa1747e014
