### ISSUE TITLE
.p4clean file is deleted if p4clean is invoked from same directory level

### ISSUE THREAD

**Issue by johntconklin** [okcompute/p4clean#5]
The .p4clean file is deleted if p4clean is invoked from the same directory where the .p4clean file is located.

This may be related to a difference between Perforce::get_untracked_files(), which returns the list of files with absolute paths, and Perforce2012::get_untracked_files(), which returns the list of files with relative paths.

With the latter implementation, the pathname passed to is_excluded() is ".p4clean", but the fnmatch pattern for the .p4clean file is "*/p4clean".

**Comment by okcompute** [comment]
The Perforce2012 implementation was removed. This problem should not occur anymore.
