### ISSUE TITLE
"Old" get_untracked_files() implementation is much faster...

### ISSUE THREAD

**Issue by johntconklin** [okcompute/p4clean#6]
Even though Perforce2012::get_untracked_files() calls "p4 status" just once and Perforce::get_untracked_files() calls "p4 fstat" twice plus walks the filesystem, the latter appears to be much faster.

This may be because p4 status does so much more (including stating and reading the contents of files), while p4 fstat fetches filenames from the server and os.walkdir() only reads directory entries.

For my client workspace (on a NFS volume), the Perforce implementation took about 45 seconds, while the Perforce2012 implementation took just under 5 minutes.

**Comment by okcompute** [comment]
Removed the Perforce2012 implementation following your observations.
