### ISSUE TITLE
Perforce::get_untracked_files() unconditionally downcases path names

### ISSUE THREAD

**Issue by johntconklin** [okcompute/p4clean#7]
The Perforce::get_untracked_files() method uses .lower() to convert path names to lower case.  This is only appropriate on case-insensitive file systems (and since some operating systems (like MacOS X) support both case-sensitive and case-insensitive filesystems, it's not as easy as an OS type check, p4clean has to check the client workspace's filesystem itself).  

One way p4clean might do this check is to create a temporary file in the workspace's root directory, and then see if it can be accessed using an all-upper or all-lower case version of the same path name.

**Comment by johntconklin** [comment]
Wonder if we could use the "Case Handling" attribute from "p4 info" for this...

**Comment by okcompute** [comment]
I removed the 'lower()' call for both the local files and the perforce depot files. This will work flawlessly under case sensitive systems. I need to test under windows if this does not cause too much problems.

**Comment by okcompute** [comment]
Is this fixed on your side with the latest code?

**Comment by johntconklin** [comment]
Pascal Lalancette notifications@github.com writes:

> Is this fixed on your side with the latest code?

Yes, it seems to be.

```
--jtc
```

## 

J.T. Conklin

**Comment by okcompute** [comment]
Cool :)
